//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MidtermMarksTable
    {
        public int Marks_id { get; set; }
        public int Subject_id { get; set; }
        public int Student_id { get; set; }
        public int Class_id { get; set; }
        public Nullable<int> Marks { get; set; }
        public string Status { get; set; }
        public int Term_id { get; set; }
        public int year_Id { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual StudentsTable StudentsTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
        public virtual Term Term { get; set; }
        public virtual Year Year { get; set; }
    }
}
