//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentsTable()
        {
            this.MidtermMarksTables = new HashSet<MidtermMarksTable>();
        }
    
        public int Student_id { get; set; }
        public string Student_Name { get; set; }
        public int Class_id { get; set; }
        public int Term_id { get; set; }
        public int year_Id { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MidtermMarksTable> MidtermMarksTables { get; set; }
        public virtual Term Term { get; set; }
        public virtual Year Year { get; set; }
    }
}
