//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjecttopic
    {
        public int Id { get; set; }
        public int Topic_id { get; set; }
        public int Term_id { get; set; }
        public int Week_id { get; set; }
        public int subject_id { get; set; }
        public int class_id { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
        public virtual Term Term { get; set; }
        public virtual TopicsTable TopicsTable { get; set; }
        public virtual WeeksTable WeeksTable { get; set; }
    }
}
