//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topicstat
    {
        public int Id { get; set; }
        public Nullable<int> value { get; set; }
        public int weekid { get; set; }
        public int Subject_id { get; set; }
        public int Topic_id { get; set; }
        public int Class_id { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
